name: My Site
remote_theme: pages-themes/modernist@v0.2.0
plugins: 
  - jekyll-remote-theme
  - jekyll-scholar
nav: 
  - title: Home
    url: /
  - title: ReadMe
    url: /readme/
  - title: Bibliography
    url /Bibliography/
